name: Android PR Test

on:
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  

    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build and run tests
      run: |
        ./gradlew clean assembleDebug test  # Adjust your build and test commands as needed
      working-directory: ./app  # Set this to your project's module directory

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: app/build/reports/tests

    - name: Set PR status
      if: always()
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/reports/tests/**/index.html
        files-upload-response: "false"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
